### ISSUE TITLE
Error: type 'Query' does not have a field 'blogIndex'

### ISSUE THREAD

**Issue by jbbae** [basehub-ai/basehub#61]
Hi, I created my first blog post using the BaseHub blog template that was created during the setup, and committed my changes.

Then I followed the steps in the attached image, which works fine (returns "{ typename: 'Query' }" successfully).
![image](https://github.com/basehub-ai/basehub/assets/12439968/a0649842-7c6e-43c4-8454-be0e4a1eb8b8)

But whenever I try to run:
```
const data = await basehub({ next: { revalidate: 30 }}).query({
    typename: true,
    blogIndex: {
      _id: true,
      blogPosts: {
        args: { first: 10, orderBy: 'publishDateDESC' },
        items: {
          _id: true,
          _title: true,
          _slug: true,
          subtitle: true,
          coverImage: { url: true },
          body: { json: true },
        },
      },
    }
  });
```

It keeps returning my this error (and I can't get my actual blog posts... What's wrong?

I already tried reinstalling - but it still doesn't work...

**Comment by julianbenegas** [comment]
Closed via Discord :)

Was a `.next` directory issue: sometimes, deleting the `.next` tells Next.js to re-compile files and modules again to reflect fresh data.
